apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dokuwiki
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dokuwiki
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dokuwiki
    spec:
      containers:
        - name: dokuwiki
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: dokuwiki-storage
              mountPath: "/storage"
      volumes:
        - name: dokuwiki-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
