apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}-dokuwiki
spec:
  type: ClusterIP  # Change to LoadBalancer if you want external access
  ports:
    - name: {{ .Release.Name }}-port
      port: 8080
      targetPort: 8080  # This should match the containerPort
  selector:
    app: {{ .Release.Name }}-dokuwiki
